# Use this file to construct an environment
# for developing scyjava from source.
#
# First, install mambaforge:
#
#   https://github.com/conda-forge/miniforge#mambaforge
#
# Then run:
#
#   mamba env create -f dev-environment.yml
#   conda activate scyjava-dev
#
# In addition to the dependencies needed for using scyjava, it
# includes tools for developer-related actions like running
# automated tests (pytest) and linting the code (black). If you
# want an environment without these tools, use environment.yml.
name: scyjava-dev
channels:
  - conda-forge
  - defaults
dependencies:
  - python >= 3.7
  # Project dependencies
  - jpype1 >= 1.3.0
  - jgo
  - openjdk
  # Test dependencies
  - numpy
  - pandas
  # Developer tools
  - autopep8
  - black
  - build
  - flake8
  - isort
  - pytest
  - pytest-cov
  - toml
  # Project from source
  - pip
  - pip:
    - validate-pyproject[all]
    - -e .
